SELECT DECREMENTA_PROD(4,2)

CREATE OR REPLACE FUNCTION DECREMENTA_PROD(COD INT,QUANTIDADE INT)
RETURNS VOID
AS $$
BEGIN
UPDATE PRODUTO SET QUANT=QUANT-QUANTIDADE WHERE COD_PROD=COD;
IF EXISTS (SELECT * FROM COMBO WHERE COD_PROD_COMBO=COD) THEN
	UPDATE PRODUTO P SET QUANT=P.QUANT-(QUANTIDADE*C.QUANT)
	FROM COMBO C
	WHERE P.COD_PROD=C.COD_PROD_COMPOE
	AND COD_PROD_COMBO=COD;
END IF;
END;
$$
LANGUAGE PLPGSQL